### ISSUE TITLE
What is the alternative of `size(width,height)`?

### ISSUE THREAD

**Issue by hunar1997** [Abdur-rahmaanJ/ppython#10]
I noticed there is not window size option, you plan to not add it or it's not implemented yet?
Thanks :D

**Comment by Abdur-rahmaanJ** [comment]
@hunar1997 yeps you can add it !

**Comment by BiscuitCandy** [comment]
@Abdur-rahmaanJ  I opened a pull-request based on this ticket

**Comment by Abdur-rahmaanJ** [comment]
@BiscuitCandy Thanks!
