### ISSUE TITLE
Remove comments

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [Abdur-rahmaanJ/ppython#7]
In template.py remove those comments
```python
#self.canvas.create_rectangle(20, 50, 200, 100, outline="black", fill="red", width=2, stipple="gray50")
#fill("orange")
#ircle(10, 10)
# ################
```
only for real first-timers

**Comment by blackfish404** [comment]
I really want to do this. Having trouble starting though, so I'm doing some research.

**Comment by Abdur-rahmaanJ** [comment]
@blackfish404 aie already solved. but feel free to add a nice snippet

**Comment by rizwansoaib** [comment]
I removed comment.

**Comment by nishu88** [comment]
Please close the issue if already solved.  :)
